---
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*

Layout/AlignArray:
  Enabled: false
Layout/AlignHash:
  EnforcedHashRocketStyle: table
Layout/AlignParameters:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: native
Layout/ExtraSpacing:
  AllowForAlignment: true
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/IndentationWidth:
  Severity: error
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/IndentHeredoc:
  Enabled: false
  Exclude:
      - spec/**/*
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/SpaceAroundOperators:
  Enabled: true
Lint/AssignmentInCondition:
  Exclude:
    - lib/mercenary/command.rb
    - lib/mercenary/option.rb
    - lib/mercenary/presenter.rb
Lint/DuplicateMethods:
  Exclude:
    - lib/mercenary/command.rb
Layout/EndAlignment:
  Severity: error
Lint/HandleExceptions:
  Exclude:
    - lib/mercenary/option.rb
Style/RescueStandardError:
  Exclude:
    - lib/mercenary/program.rb
Lint/UselessAssignment:
  Exclude:
    - lib/mercenary/presenter.rb
Lint/UnreachableCode:
  Severity: error
Lint/UselessAccessModifier:
  Enabled: false
Lint/Void:
  Enabled: false
Metrics/AbcSize:
  Max: 21
  Exclude:
    - lib/mercenary/program.rb
Metrics/BlockLength:
  Exclude:
    - examples/**/*
    - spec/**/*
Metrics/ClassLength:
  Max: 300
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/LineLength:
  Exclude:
    - lib/mercenary/command.rb
    - lib/mercenary/presenter.rb
    - lib/mercenary/program.rb
    - examples/**/*
    - spec/**/*
    - mercenary.gemspec
  Max: 90
  Severity: warning
Metrics/MethodLength:
  Exclude:
    - lib/mercenary/program.rb
  CountComments: false
  Max: 20
  Severity: error
Metrics/ModuleLength:
  Max: 240
Metrics/ParameterLists:
  Max: 4
Metrics/PerceivedComplexity:
  Max: 8
Naming/FileName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/PredicateName:
  Exclude:
    - lib/mercenary/command.rb
Style/Alias:
  Enabled: false
Style/AndOr:
  Severity: error
Style/Attr:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - lib/mercenary/command.rb
  Enabled: true
  EnforcedStyle: always
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Severity: error
Style/IfUnlessModifier:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/MissingRespondToMissing:
  Exclude:
    - lib/mercenary/presenter.rb
Style/ModuleFunction:
  Enabled: false
Style/MultilineTernaryOperator:
  Severity: error
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%q": "{}"
    "%Q": "{}"
    "%r": "!!"
    "%s": "()"
    "%w": "()"
    "%W": "()"
    "%x": "()"
Style/RedundantReturn:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: percent_r
Style/RescueModifier:
  Enabled: false
Style/SignalException:
  EnforcedStyle: only_raise
Style/SingleLineMethods:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/UnneededCapitalW:
  Enabled: false
