language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
sudo: false
cache: bundler
before_script: bundle update
script: script/cibuild
notifications:
  email:
    recipients:
      - mercenary@jekyllrb.com
    on_success: change
    on_failure: change
