name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    name: 'Ruby ${{ matrix.ruby_version }}'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.7
          - 3.3
          - 3.4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Execute Unit tests
        run:  script/cibuild

  style_check:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    name: 'Code Style Check'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.7
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Run RuboCop
        run:  bash script/fmt
